package customer

import (
	"encoding/json"
	"net/http"
)

type Handler struct {
	service Service
}

func NewHandler(service Service) *Handler {
	return &Handler{service: service}
}

func (handler *Handler) Create(res http.ResponseWriter, req *http.Request) {
	res.Header().Set("Content-Type", "application/json")

	var body CreateCustomerRequest
	err := json.NewDecoder(req.Body).Decode(&body)
	if err != nil {
		http.Error(res, err.Error(), http.StatusBadRequest)
		return
	}

	newCustomer := &Customer{
		ID:        "123", // ID will be generated by the service
		FirstName: body.FirstName,
		LastName:  body.LastName,
		Email:     body.Email,
		Language:  body.Language,
	}

	err = handler.service.CreateCustomer(newCustomer)
	if err != nil {
		http.Error(res, err.Error(), http.StatusInternalServerError)
		return
	}

	response := CreateCustomerResponse{
		ID:        newCustomer.ID,
		FirstName: newCustomer.FirstName,
		LastName:  newCustomer.LastName,
		Email:     newCustomer.Email,
		Language:  newCustomer.Language,
	}

	json.NewEncoder(res).Encode(response)

}
